### ISSUE TITLE
Grammar Error

### ISSUE THREAD

**Issue by PatCer** [HeidrichJannic/DevOps#1]
## Description

(Line numbers are from the raw file)
Line 2 : "Afterwards, the sends message..."
Line 4 : "Firstly, variables are... such as IoT Hub name... etc. In addition, a ..."
Line 27 : "As soon as the send is complete..."
Line 33 : "as the message send." "If one of these is not the case"

## Location

Two_Three/UserStory3-Doc.md

## Suggested Correction

Line 2 : "Afterwards, the sent message..."
Line 4 : "Firstly, some variables" "such as the IoT Hub name" "etc. and in addition a"
Line 27 : "As soon as the sending process is complete"
Line 33 : "as the message sent." "If this is not the case"

## Screenshots

1.:
![image](https://github.com/HeidrichJannic/DevOps/assets/150437961/378e17a4-11d6-4099-bb4f-f273ebc0db6e)

2.:
![image](https://github.com/HeidrichJannic/DevOps/assets/150437961/7f602b94-59aa-4471-aa6a-b5b6de384dbf)

3.:
![image](https://github.com/HeidrichJannic/DevOps/assets/150437961/1a6f3e57-da3b-4087-9f92-3494c5171410)

**Comment by HeidrichJannic** [comment]
Hi @PatCer ,
thank you for your issue description. I will start revising my documentation as soon as possible and will then let you know. 
Heidrich Jannic

**Comment by HeidrichJannic** [comment]
Hi @PatCer ,
the documentation has been revised, if you find any more mistakes please let me know.
Heidrich Jannic
